@Lab2_HostAddress = http://localhost:5059

POST {{Lab2_HostAddress}}/advertisment
Content-Type: application/json

{
  "description": "Brand new Iphone 11",
  "price": 399.99,
  "datePosted": "2024-10-14T00:00:00Z",
  "sellerId": 1,
  "categoryId": 1
}
###

PUT {{Lab2_HostAddress}}/advertisment/1
Content-Type: application/json

{
  "description": "kiwi",
  "category": "fruit",
  "price": 2
}

###

DELETE {{Lab2_HostAddress}}/advertisment/2


###

GET {{Lab2_HostAddress}}/categories

###

GET {{Lab2_HostAddress}}/sellers

###

GET {{Lab2_HostAddress}}/advertisment

###
